export type Mode = "Light" | "Dark" | "System" | "Undefined"
export const LightMode = "Light"
export const DarkMode = "Dark"
export const SystemMode = "System"
export const UndefinedMode = "Undefined"